### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by ay8s** [calvinmclean/homebridge-kettle#1]
Hey @calvinmclean.

I'd love to try and set this up on my Homebridge server. Curious if there are any details on the configuration for this? It looks like it needs to be manually set within the implementation and consists of the serial number? I've seen a few other examples for EKG that use the MAC address so just wanted to confirm. 👍 

Thanks for putting this together.

**Comment by calvinmclean** [comment]
Hi, sorry for the late response. I have been meaning to improve the documentation here so thanks for the reminder.

I'm pretty new to Homebridge and Node in general so this is a pretty basic setup strapped together from documentation and tutorials. All the actual interaction with the Stagg EKG is done by a [Python program](https://github.com/calvinmclean/stagg-ekg-plus) this this uses over HTTP requests.

My `config.json` just looks like this and came from an example config:
```json
{
  "bridge": {
    "name": "Homebridge",
    "username": "CC:22:3D:E3:CE:41",
    "port": 51826,
    "pin": "031-45-154",
    "room": "Kitchen"
  },
  
  "description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",
  "ports": {
    "start": 52100,
    "end": 52150,
    "comment": "This section is used to control the range of ports that separate accessory (like camera or television) should be bind to."
  },
  "accessories": [
    {
      "accessory": "MyKettle",
      "room": "Kitchen",
      "name": "Kettle"
    }
  ]
}
```

Even the MAC address used as the `username` is made up here. The Python program I mentioned does use the MAC address to communicate with the kettle. I will also plan to make some changes there to improve usability and documentation since I kind of stopped putting as much work into this once I got it working :laughing:

**Comment by ay8s** [comment]
All good. I've set up a different plugin but will try and switch it over to this one tomorrow as it seems to offer a few additional features. The Python was the missing bit I needed. :)  

Edit: Not sure how I missed it. 

Thanks for detailing all that!
